---
title: "week12_Practice_Visualization"
author: "yjiang"
date: "7/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
# Model Diagnostics
## Check the assumptions of
### y = 3 + 5x + ϵ, ϵ ~N (0,1)  * Will use this as example
sim_1 = function(sample_size = 500) {
  x = runif(n = sample_size) * 5
  y = 3 + 5 * x + rnorm(n = sample_size, mean = 0, sd = 1)
  data.frame(x, y)}

### y = 3 + 5x + ϵ, ϵ ~N (0,x^2)
sim_2 = function(sample_size = 500) {
  x = runif(n = sample_size) * 5
  y = 3 + 5 * x + rnorm(n = sample_size, mean = 0, sd = x)
  data.frame(x, y)}

### y = 3 + 5x + ϵ, ϵ ~N (0,25)
sim_3 = function(sample_size = 500) {
  x = runif(n = sample_size) * 5
  y = 3 + 5 * x ^ 2 + rnorm(n = sample_size, mean = 0, sd = 5)
  data.frame(x, y)}


## Check fitted vs residuals plot
### Set the seed
set.seed(35)
sim_data_1 = sim_1()
head(sim_data_1)

## Fitted plot
plot(y ~ x, data = sim_data_1, col = "red", pch = 20,
     main = "Model 1")
fit_1 = lm(y ~ x, data = sim_data_1)
abline(fit_1, col = "darkorange", lwd = 3)

## Fitted and residuals plot
plot(fitted(fit_1), resid(fit_1), col = "red", pch = 20,
     xlab = "Fitted", ylab = "Residuals", main = "Model 1")
abline(h = 0, col = "darkorange", lwd = 2)


```
```{r}
# Histograms
par(mfrow = c(1, 3))

## Print the result
hist(resid(fit_1),
     xlab   = "Residuals",
     main   = "Histogram_fit1",
     col    = "gray",
     border = "dodgerblue",
     breaks = 20)

# Q-Q plots
qqnorm(resid(fit_1), main = "Q-Q Plot_fit1", col = "green")
qqline(resid(fit_1), col = "dodgerblue", lwd = 2)



```
```{r}
# Shapiro_Wilk test
## Set the seed as 35
set.seed(35)

## Test the shapiro with 25
shapiro.test(rnorm(25))
   ### or
shapiro.test(rexp(25))
   ### or
shapiro.test(resid(fit_1))

```
```{r}
# Chech the unusual observation
## Set the database
par(mfrow = c(1, 3))
set.seed(35)
ex_data  = data.frame(x = 1:10,
                      y = 10:1 + rnorm(n = 10))
ex_model = lm(y ~ x, data = ex_data)

# Check with a low leverage, large residual, small influence
point_1 = c(5.4, 11)
ex_data_1 = rbind(ex_data, point_1)
model_1 = lm(y ~ x, data = ex_data_1)
plot(y ~ x, data = ex_data_1, cex = 2, pch = 20, col = "grey",
     main = "Low_Leverage, Large_Residual, Small_Influence")
points(x = point_1[1], y = point_1[2], pch = 1, cex = 4, col = "red", lwd = 5)
abline(ex_model, col = "green", lwd = 2)
abline(model_1, lty = 2, col = "darkgray", lwd = 2)
legend("bottomleft", c("Original Data", "Added Point"),
       lty = c(1, 2), col = c("green", "darkgray"))


```
```{r}
# Leverage_could have large influence 
## Determine the lev_1 with a df
lev_1 = data.frame(
  x1 = c(0, 11, 11, 7, 4, 10, 5, 8),
  x2 = c(1, 5, 4, 3, 1, 4, 4, 2),
  y  = c(11, 15, 13, 14, 0, 19, 16, 8))

## Print the result
plot(x2 ~ x1, data = lev_1, cex = 2)
points(7, 3, pch = 20, col = "green", cex = 2)


```









